### PR TITLE
Syntax 2.1

### PR DESCRIPTION
**Pull request by fitomad**
Updated to Swift 2.1 syntax...

+ repeat-while 
+ do-catch
+ guard, defer, try, throw, throws

Include public, internal and private
Include Void as data type

### CODE REVIEW

**Comment by damirstuhec** [comment]
Why aren't you merging this PR?

**Comment by damirstuhec** [comment]
@quiqueg why isn't this PR merged?

**Comment by halfnibble** [comment]
That is still an excellent question to this day.

**Comment by quiqueg** [comment]
Hey guys, sorry about the delay, GitHub notifications weren't making it to my email inbox.

Swift.YAML-tmLanguage needs to be updated as well, since that is the preferred format for syntax development.  The others files are compiled by PackageDev from the YAML file.

I'll merge this now and add the changes to the YAML file, then make a new release.

Thanks for the PR!

**Pull request merged**
